### ISSUE TITLE
Doesn't works anymore with the new Facebook interface

### ISSUE THREAD

**Issue by Aleck85** [Narno/F-Notifier#25]
Doesn't work with the new Facebook interface
![Аннотация 2020-03-21 085139](https://user-images.githubusercontent.com/5072865/77220389-a9e2f300-6b50-11ea-8dea-03abe4719b41.png)

**Comment by Narno** [comment]
Hello @Aleck85, I will try to fix that when my FB account will be eligible to the new UI.

**Comment by Narno** [comment]
Hello @Aleck85, this probleme should be fixed with the 2.4.1 version. Thx.
