### ISSUE TITLE
Doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by Aleck85** [Narno/F-Notifier#37]
It shows a gray question mark sign in the icon. Logging out of Facebook then logging back in doesn't seem to fix the issue. In Chrome and Vivaldi works well. Please fix it.

**Comment by Narno** [comment]
Hello, it should be fixed in the next release (Pending review).

**Comment by Narno** [comment]
Related to #35.

**Comment by Narno** [comment]
The Edge version of the extension is now available at https://microsoftedge.microsoft.com/addons/detail/fnotifier/jkpbopolkbhegaabkoljoofcfingihlp.
